const ALL_SEARCH_RESULTS = {
    accountResults: [
      {
        name: 'some_org',
        id: '3715d177-e248-4f38-9997-eb27b331003b',
        fullName: '',
        isOrg: true,
        membersCount: 1,
      },
      {
        name: 'some_user',
        id: 'c25ed90f-4757-47a3-a06d-f88a9879cb39',
        fullName: '',
        isOrg: false,
        isAdmin: false,
        isActive: true,
        isImported: false,
      },
      {
        name: 'other_org',
        id: '3715d177-e248-4f38-9997-eb27b331003c',
        fullName: '',
        isOrg: true,
        membersCount: 1,
      },
      {
        name: 'other_user',
        id: 'c25ed90f-4757-47a3-a06d-f88a9879cb30',
        fullName: '',
        isOrg: false,
        isAdmin: false,
        isActive: true,
        isImported: false,
      },
    ],
    repositoryResults: [
      {
        id: '11f35fd0-617f-49fa-9a34-16946f2870bb',
        namespace: 'admin',
        namespaceType: 'user',
        name: 'some_repository',
        shortDescription: '',
        visibility: 'public',
        scanOnPush: false,
        immutableTags: false,
        enableManifestLists: false,
        pulls: 0,
        pushes: 0,
        tagLimit: 0,
      },
      {
        id: '11f35fd0-617f-49fa-9a34-16946f2870bb',
        namespace: 'slightlytyler',
        namespaceType: 'user',
        name: 'other_repository',
        shortDescription: '',
        visibility: 'public',
        scanOnPush: false,
        immutableTags: false,
        enableManifestLists: false,
        pulls: 0,
        pushes: 0,
        tagLimit: 0,
      },
    ],
};

export default ALL_SEARCH_RESULTS;
